
services:
  mysql:
    image: mysql:8.0
    container_name: mysql
    restart: unless-stopped
    environment:
      MYSQL_ROOT_PASSWORD: demo
      MYSQL_DATABASE: demo
      MYSQL_USER: demouser
      MYSQL_PASSWORD: demopasswd
    ports:
      - "3306:3306" # Expose MySQL on host port 3306
    healthcheck:
      test: ["CMD-SHELL", "timeout 1 bash -c 'cat < /dev/null > /dev/tcp/localhost/3306'"]
      interval: 5s
      timeout: 3s
      retries: 3

#    volumes:
#      - mysql_data:/var/lib/mysql # Persist data
    # Optional: Set default character set and collation
    # command: --character-set-server=utf8mb4 --collation-server=utf8mb4_unicode_ci

  boilerplate:
    #build: .
    #container_name: micronaut-boilerplate
    image: micronaut-boilerplate-image:0.1-qa
    restart: unless-stopped
    ports:
      - "8080:8080" # Expose Micronaut application on host port 8080
    environment:
        # Optional: Database connection settings
        MYSQL_URL: jdbc:mysql://mysql:3306/demo?allowPublicKeyRetrieval=true&useSSL=true
        MYSQL_DATABASE: demo
        MYSQL_USER: demouser
        MYSQL_PASSWORD: demopasswd
        # Optional: Other environment variables for your application
        # JAVA_OPTS: -Xmx512m
    depends_on:
      - mysql

#volumes:
#  mysql_data: # Define the named volume for data persistence
