SET @USER_NAME = CONCAT(@MYSQL_USER, "@'%'");

SET @CREATE_SCHEMA = CONCAT('CREATE SCHEMA ', @MYSQL_DBNAME, ' DEFAULT CHARACTER SET utf8');
PREPARE s1 FROM @CREATE_SCHEMA;
EXECUTE s1;

SET @CREATE_USER = CONCAT('CREATE USER ', @MYSQL_USER, ' IDENTIFIED BY "', @MYSQL_PASSWORD, '"');
PREPARE s2 FROM @CREATE_USER;
EXECUTE s2;

SET @GRANT_PRIV = CONCAT('GRANT ALL PRIVILEGES ON ', @MYSQL_DBNAME, '.* TO ', @MYSQL_USER);
PREPARE s3 FROM @GRANT_PRIV;
EXECUTE s3;