SET @USER_NAME = CONCAT(@MYSQL_USER, "@'%'");

SET @DROP_SCHEMA = CONCAT('DROP DATABASE IF EXISTS ', @BOILERPLATE_MYSQL_DBNAME);
PREPARE s0 FROM @DROP_SCHEMA;
EXECUTE s0;

SET @CREATE_SCHEMA = CONCAT('CREATE SCHEMA IF NOT EXISTS ', @BOILERPLATE_MYSQL_DBNAME, ' DEFAULT CHARACTER SET utf8');
PREPARE s1 FROM @CREATE_SCHEMA;
EXECUTE s1;

SET @CREATE_USER = CONCAT('CREATE USER IF NOT EXISTS ', @BOILERPLATE_MYSQL_USER, ' IDENTIFIED BY "', @BOILERPLATE_MYSQL_PASSWORD, '"');
PREPARE s2 FROM @CREATE_USER;
EXECUTE s2;

SET @GRANT_PRIV = CONCAT('GRANT ALL PRIVILEGES ON ', @BOILERPLATE_MYSQL_DBNAME, '.* TO ', @BOILERPLATE_MYSQL_USER);
PREPARE s3 FROM @GRANT_PRIV;
EXECUTE s3;