micronaut:
  application:
    name: demo
  router:
    static-resources:
      swagger:
        paths: classpath:META-INF/swagger
        mapping: /swagger/**
      redoc:
        paths: classpath:META-INF/swagger/views/redoc
        mapping: /redoc/**
      rapidoc:
        paths: classpath:META-INF/swagger/views/rapidoc
        mapping: /rapidoc/**
      swagger-ui:
        paths: classpath:META-INF/swagger/views/swagger-ui
        mapping: /swagger-ui/**
  security:
    intercept-url-map:
      - pattern: /swagger/**
        http-method: GET
        access:
          - isAnonymous()
    enabled: true
    endpoints:
      login:
        enabled: true
      logout:
        enabled: false
      oauth:
        enabled: false
    authentication: bearer
    token:
      jwt:
        generator:
          access-token:
            expiration: ${APPFACTORY_ACCESS_TOKEN_EXPIRATION:18000}  # 5 hours
        cookie:
          enabled: false
        signatures:
          secret:
            generator:
              secret: ${APPFACTORY_JWT_SECRET:X4Tc6Qa5Cr<6xt{eZ/3AC93|B5iF]0;G0vH+AT=g*{5/_93)q,*M[T8Jbispbd5vb6S-4[f^}

############################# DB ################################

dataSource:
  #  dbCreate: none, update, or create-drop
  dialect: org.hibernate.dialect.MySQL5InnoDBDialect
  url: ${MYSQL_URL:`jdbc:mysql://localhost:6603/demo?useSSL=false`}
  username: ${MYSQL_USER:demouser}
  password: ${MYSQL_PASSWORD:demopasswd}
  driverClassName: com.mysql.cj.jdbc.Driver
  pooled: true
  #  jmxExport: true
  maximumPoolSize: ${DB_MAX_POOL_SIZE:10}
  minimumIdle: 5

hibernate:
  show_sql: false
  hbm2ddl:
    auto: none
  cache:
    queries: false
    use_second_level_cache: false
    use_query_cache: false

flyway:
  datasources:
    default:
      locations:
        - classpath:dbmigrations
        - classpath:com/myexample/dbmigrationscript
      baseline-on-migrate: true