micronaut:
  application:
    name: boilerplate
#datasources:
#  default:
#    driverClassName: com.mysql.cj.jdbc.Driver
#    db-type: mysql
#    dialect: MYSQL
#netty:
#  default:
#    allocator:
#      max-order: 3
#jpa:
#  default:
#    properties:
#      hibernate:
#        hbm2ddl:
#          auto: none
