micronaut:
  application:
    name: boilerplate
  server:
    port: ${BOILERPLATE_PORT:8080}
  security:
    authentication: bearer
    token:
      jwt:
        signatures:
          secret:
            generator:
              secret: '"${JWT_GENERATOR_SIGNATURE_SECRET:kWfCD!1yy3FQQTEK#Tpx^WoqF&isJqr2gJsUM0Tu!HtlN7^o5b}"'
datasources:
  default:
    driverClassName: com.mysql.cj.jdbc.Driver
    db-type: mysql
    dialect: MYSQL
    url: ${BOILERPLATE_MYSQL_URL:`jdbc:mysql://localhost:3306/demo?allowPublicKeyRetrieval=true&useSSL=false`}
    username: ${BOILERPLATE_MYSQL_USER:demouser}
    password: ${BOILERPLATE_MYSQL_PASSWORD:demopasswd}
    minPoolSize: 1
    maxPoolSize: ${MYSQL_MAXPOOLSIZE:5}
netty:
  default:
    allocator:
      max-order: 3
jpa:
  default:
    properties:
      hibernate:
        format_sql: false
        show_sql: false
        hbm2ddl:
          auto: none

flyway:
  datasources:
    default:
      enabled: true
      locations:
        - classpath:dbmigrations
        - classpath:com/example/dbmigrationscript/v1
      baseline-on-migrate: true